### ISSUE TITLE
How to use the existing data for classification?

### ISSUE THREAD

**Issue by Linkersem** [kailugaji/GaussianMixtureModel-clustering#1]
I have a set of one-dimensional data and need to use the EM algorithm to calculate the mean and standard deviation of each Gaussian distribution, but this algorithm seems to only use the data generated by itself?

**Comment by kailugaji** [comment]
I just updated a repository.   
You can refer to this Matlab code: [https://github.com/kailugaji/Gaussian_Mixture_Model_for_Clustering](https://github.com/kailugaji/Gaussian_Mixture_Model_for_Clustering)  

If you only fit one-dimensional data, you can consider using this matlab function ‘fitgmdist()’  
Refer to [https://www.mathworks.com/help/stats/fitgmdist.html](https://www.mathworks.com/help/stats/fitgmdist.html)    
[https://www.mathworks.com/help/stats/fit-a-gaussian-mixture-model-to-data.html](https://www.mathworks.com/help/stats/fit-a-gaussian-mixture-model-to-data.html)  

Chinese version: [MATLAB用“fitgmdist”函数拟合高斯混合模型(一维数据)](https://www.cnblogs.com/kailugaji/p/12158825.html)

**Comment by Linkersem** [comment]
Thank you very much for your help, the method you provided has a great meaning to my question.
